### PR TITLE
Improve Readme, Add Spirit-Body

### PR DESCRIPTION
**Pull request by dodekeract**

### CODE REVIEW

**Comment by hnry** [comment]
Thanks for the pull, appreciate the corrections to the README.

Everything looks good, but how does it sound if there is a distinction between the 'officially' supported components and third party ones? 

How does `## Components` and adding another section `## Third Party Components` sound?

**Comment by dodekeract** [comment]
@hnry Sure, sounds good. I'll get back to this later today.

**Comment by dodekeract** [comment]
What do you think about changing `Components` to `Middleware` and excluding `spirit` itself (it's kind of redundant anyway)?

**Comment by hnry** [comment]
I want to give a overview of the all the parts of spirit, and think components is probably better since I want to make clear they aren't middleware per se, but each part can be replaced like even the router.

**Pull request merged**
